Lection 3, button finished
js-tasks-ru/htmlcss-20210812_info6 pull request #9
Opened 2021-09-16 15:29 UTC by stunzyk

2021-09-16 15:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-20 09:29 UTC, GSemikozov requested changes

2021-09-20 09:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary {
распишу в одном комментарии:
1. нужно в общем классе блока .button описать всё то, что является общим для всех типов кнопок, чтобы каждый раз не дублировать стили
2. В модификаторы добавить только то, что специфическим образом модифицирует кнопку (в основном фон и цвет текста) 
3. модификаторы задаются через одно нижнее подчеркивание `_` (через два - это элементы блока)
4. все цвета важно протавлять из css-переменных
5. для disabled вместо указания другого цвета фона и курсора достаточно добавить pointer-events: none (не даст возможность пользователю нажимать на такой элемент + курсор будет по умолчанию default)
6. .button__preview - тоже должен быть модификатор

2021-09-21 18:44 UTC, GSemikozov requested changes

2021-09-21 18:44 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    /*.button как таковой имеет все настройки primary по умолчанию. Мне кажется хоть и пустым - но лучше оставить, что бы не искали. И вообще - не имеет ли смысл вообще убрать button__primary и испол
вот как раз здесь, поскольку мы описываем специфический тип кнопки, мы и должны определить фон и цвет которые сейчас добавлены глобально на уровне .button :) это важно прежде всего с точки зрения семантики - использую модификатор мы четко понимает что речь о primary кнопке, а не абстрактно о кнопке вообще

2021-09-22 18:31 UTC, GSemikozov approved these changes

2021-09-22 18:32 UTC, merged